language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: $HEROKU_APP_NAME
    github_token: $GITHUB_TOKEN
    google_api_key: $GOOGLE_API_KEY
  
install:
  - npm i
